### ISSUE TITLE
can't active your add-on from assets-lib

### ISSUE THREAD

**Issue by qza2468** [night-glider/Dialogue-Label#1]
I download this add-on from the assets-lib, and when activate it, it turns out like this, what should i do, or maybe there should be some fix.
Wondering :)
I'm in Godot4.02, Ubuntu22.04.
![image](https://user-images.githubusercontent.com/70065298/235066178-78b6a5a1-414e-462b-8c10-71115ac8c73b.png)

**Comment by night-glider** [comment]
Whoops, i thought dialogue_label.gd is optional... Sorry for that!
Fixed it in latest commit.
Asset lib takes time to update, so consider downloading addon from github directly for now
